# Generated by Django 5.2.5 on 2025-09-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_pokemon_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='name',
            new_name='title_ru',
        ),
    ]
